name: Build all (reuseable)

on:
    push:
      branches:
       - main
      paths:
       - 'deps/**'
       - 'src/**'
       - '**/CMakeLists.txt'
       - 'version.inc'
       - 'localization/**'
       - 'resources/**'
       - ".github/workflows/build_all.yml"

    pull_request:
      branches:
       - main
      paths:
       - 'deps/**'
       - 'src/**'
       - '**/CMakeLists.txt'
       - 'version.inc'
       - ".github/workflows/build_all.yml"

    workflow_dispatch: # allows for manual dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  check_cache: # determines if there is a cache and outputs variables used in cacheing process
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
          - os: windows-latest
          - os: macos-12
            arch: x86_64
          - os: macos-12
            arch: arm64
    runs-on: ${{ matrix.os }}
    outputs:
      cache-hit: ${{ steps.cache_deps.outputs.cache-hit }}
      json-output: ${{ steps.outputs.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: set outputs
        id: set_outputs
        uses: cloudposse/github-action-matrix-outputs-write@main
        env:
          # helper vars to make more readable
          underscore-arch: ${{ matrix.os == 'macos-12' && '_' || ''}}${{ matrix.os == 'macos-12' && matrix.arch || '' }} # if is macos, make a string that does "_{arch}", else output nothing
          dash-arch: ${{ matrix.os == 'macos-12' && '-' || ''}}${{ matrix.os == 'macos-12' && matrix.arch || '' }} # if is macos, make a string that does "-{arch}", else output nothing
          dep-folder-name: ${{ (matrix.os == 'windows-latest' || matrix.os == 'macos-12') && 'OrcaSlicer_dep' || 'destdir' }}
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.os }}${{ matrix.arch }}
          outputs: |-
            cache-name: ${{ runner.os }}${{ env.dash-arch }}-cache-orcaslicer_deps
            cache-path: ${{ github.workspace }}/deps/build${{ env.underscore-arch }}/${{ env.dep-folder-name }}${{ env.underscore-arch }}
            hash: ${{ hashFiles('deps/**') }}
            
      - name: load cache
        id: cache_deps
        uses: actions/cache@v3
        env:
          vars: ${{ steps.set_outputs.outputs.result }}
          matrix-key: ${{ matrix.os }}${{ matrix.arch }}
        with:
          path: ${{ fromJson(env.vars).cache-path }}
          key: ${{ fromJson(env.vars).cache-name }}-build-${{ fromJson(env.vars).hash }} # hash of deps folder used to only rebuild if deps are modified
          
      - name: set validity output
        uses: cloudposse/github-action-matrix-outputs-write@main
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.os }}${{ matrix.arch }}
          outputs: |-
            valid-cache: ${{ steps.cache_deps.outputs.cache-hit || false }}
            
      - name: load final check_cache outputs
        id: outputs
        uses: cloudposse/github-action-matrix-outputs-read@main
        with:
          matrix-step-name: check_cache
          
  delete_extra_archives:
    needs: [check_cache]
    runs-on: ubuntu-20.04
    steps:
      - name: delete artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: |
            *
        
  build_all:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
          - os: windows-latest
          - os: macos-12
            arch: x86_64
          - os: macos-12
            arch: arm64
    needs: [check_cache]
    uses: ./.github/workflows/build_deps.yml
    with:
      cache-path: ${{ fromJson(needs.check_cache.outputs.json-output).cache-path[format('{0}{1}', matrix.os, matrix.arch)] }}
      cache-name: ${{ fromJson(needs.check_cache.outputs.json-output).cache-name[format('{0}{1}', matrix.os, matrix.arch)] }}
      valid-cache: ${{ fromJson(needs.check_cache.outputs.json-output).valid-cache[format('{0}{1}', matrix.os, matrix.arch)] }}
      hash: ${{ fromJson(needs.check_cache.outputs.json-output).hash[format('{0}{1}', matrix.os, matrix.arch)] }}
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}